# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7135f3f8356b5fead1d5fbc087d0bf4fce7a3326b565e154fbb0586760a90145bf2f8b3ccecf0071f722bc6216d331bbd2618f3909944a6c26631f0b60360c4

test:
  secret_key_base: 0e146a07b7a8566d65a92e3c1853665dd768c1c07a093c10cf9559da545890ec50c41eca6929a8ffc27bec22469f982bc68a02ea8057ade9ef6bf55fa2bc3041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
